version: '2'

services:
  test-new-java:
    build:
      context: test/
      dockerfile: Dockerfile-new-java
    environment:
      TZ: America/Sao_Paulo
    depends_on:
      - database
    links:
      - database
  test-old-java:
    build:
      context: test/
      dockerfile: Dockerfile-old-java
    environment:
      TZ: America/Sao_Paulo
    depends_on:
      - database
    links:
      - database
  database:
    image: postgres:9.6
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./database:/docker-entrypoint-initdb.d
